### PR TITLE
Il develop

### PR DESCRIPTION
**Pull request by Laganellac**
This branch contains routines to write/read FmsDataCollections as well as an update to the CMake logic to include googletest (for unit tests) and optionally link in Conduit. This branch also includes a couple additions to the examples directory.

### CODE REVIEW

**Comment by Laganellac** [comment]
The updates to this branch include the work we've done for milestone 2 of our FMS work. This includes the addition of unit tests for the FmsIO functions, a "compare" interface in Fms.h which is used by the tests (and potential future tests), and support for writing/reading using Conduit binary protocols.

**Review by tzanio — APPROVED** [review]
Thanks @Laganellac !

**Comment by v-dobrev** [comment]
This was not ready for merging. I have not reviewed it.

**Comment by Laganellac** [comment]
@v-dobrev Sorry! Would you like me to revert the merge?

**Comment by v-dobrev** [comment]
> @v-dobrev Sorry! Would you like me to revert the merge?

No, no need. I'll make another PR if I have changes.

**Pull request merged**
